# Generated by Django 4.2.2 on 2023-06-28 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
